myproject/models.py
from myproject import db

class Puppy(db.Model):
    __tablename__ = 'puppies'
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.Text)
    owner = db.relationship('Owner', backref = 'Puppy', uselist = False)
    def __init__(self, name):
        self.name = name
    def __repr__(self):
        if self.owner:
            return f"Puppy name is {self.name} and the owner is {self.owner.name}"
        else:
            return f"Puppy name is {self.name} and no owner assigned yet."

class Owner(db.Model):
    __tablename__ = 'owners'
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.Text)
    puppy_id = db.Column(db.Integer, db.ForeignKey('puppies.id'))
    def __init__(self, name, puppy_id):
        self.name = name
        self.puppy_id = puppy_id
    def __repr__(self):
        return f"Owner Name: {self.name}"

myproject/owners/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):
    name = StringField('Name of Owner: ')
    pup_id = IntegerField('ID Number of Puppy: ')
    submit = SubmitField('Add Owner')

myproject/puppies/forms.py
# forms.py file
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):
    name = StringField('Name of Puppy: ')
    submit = SubmitField('Add Puppy')

class DelForm(FlaskForm):
    id = IntegerField('ID Number of Puppy to Remove: ')
    submit = SubmitField('Remove Puppy')

myproject/__init__.py
# adoption_site.py
import os
# from forms import AddForm, DelForm, AddOwnerForm
from flask import Flask, render_template, url_for, redirect
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)
app.config['SECRET_KEY'] = 'mysecretkey'

basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///'+ os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app, db)

from myproject.puppies.views import puppies_blueprints
from myproject.owners.views import owners_blueprints

app.register_blueprint(owners_blueprints, url_prefix = '/owners')
app.register_blueprint(puppies_blueprints, url_prefix = '/puppies')

myproject/owners/views.py
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.models import Owner
from myproject.owners.forms import AddForm

owners_blueprints = Blueprint('owners', __name__, template_folder='templates/owners')

@owners_blueprints.route('/add', methods = ['GET', 'POST'])
def add():
    form = AddForm()
    if form.validate_on_submit():
        name = form.name.data
        pup_id = form.pup_id.data
        new_owner = Owner(name, pup_id)
        db.session.add(new_owner)
        db.session.commit()
        return redirect(url_for('puppies.list'))
    return render_template('add_owner.html', form = form)

myproject/puppies/views.py
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.models import Puppy
from myproject.puppies.forms import AddForm, DelForm

puppies_blueprints = Blueprint('puppies', __name__, template_folder='templates/puppies')

@puppies_blueprints.route('/add', methods = ['GET', 'POST'])
def add():
    form = AddForm()
    if form.validate_on_submit():
        name = form.name.data
        new_pup = Puppy(name)
        db.session.add(new_pup)
        db.session.commit()
        return redirect(url_for('puppies.list'))
    return render_template('add.html', form = form)

@puppies_blueprints.route('/list')
def list():
    puppies = Puppy.query.all()
    return render_template('list.html', puppies = puppies)

@puppies_blueprints.route('/delete', methods = ['GET', 'POST'])
def delete():
    form = DelForm()
    if form.validate_on_submit():
        id = form.id.data
        pup = Puppy.query.get(id) # not Puppy(id)!
        db.session.delete(pup)
        db.session.commit()
        return redirect(url_for('puppies.list'))
    return render_template('delete.html', form = form)

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
    <title>Document</title>
</head>
<body>
    <!-- <nav class = 'navbar navbar-expand-lg bg-body-tertiary'>
        <div class="container-fluid">
            <div class="navbar-nav">
                <a class="navbar-brand" href="#">Navbar</a>
                <a class = "nav-item nav-link" href="{{'index'}}">Home</a>
                <a class = "nav-item nav-link" href="{{'add_pup'}}">Add Pup</a>
                <a class = "nav-item nav-link" href="{{'list_pup'}}">List of Pup</a>
                <a class = "nav-item nav-link" href="{{'del_pup'}}">Delete Pup</a>
            </div>
        </div>
    </nav> -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Puppy Adoption</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('index')}}">Home</a>
                </li>
                <li class="nav-item">
                    <a class = "nav-link" href="{{url_for('puppies.add')}}">Add Pup</a>
                </li>
                    <a class = "nav-link" href="{{url_for('puppies.list')}}">List of Pup</a>
                </li>
                    <a class = "nav-link" href="{{url_for('puppies.delete')}}">Delete Pup</a>
                    <!-- <a class="nav-link" href="#">Link</a> -->
                </li>
                </li>
                    <a class = "nav-link" href="{{url_for('owners.add')}}">Add Owner</a>
                    <!-- <a class="nav-link" href="#">Link</a> -->
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            </div>
        </div>
      </nav>
    {%block content%}

    {%endblock%}
</body>
</html>

myproject/templates/home.html
{%extends "base.html"%}
{%block content%}
<div class="jumbotron">
    <h1>Welcome to our Adoption Page</h1>
    <p>Please select one of the links from the navigation panel.</p>
</div>
{%endblock%}